name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Ensure data folder exists with placeholder
      run: |
        mkdir -p ./data
        touch ./data/.gitkeep

    # Move the database to the correct location for your app
    - name: Move DB to the app folder
      run: |
        mv ./data/posted_articles.db ./PostDevToLi/posted_articles.db
      continue-on-error: true
    - name: Run Application (or Tests)
      run: |
        dotnet run --project PostDevToLi/PostDevToLi.csproj -- \
        --api-key=42vErWKs2oipGf6pYuBWnQPt \
        --access-token=AQXD2BR_zOyTZ7bQlUkm0KNNfm4PwjpxupMQ_M1rowTA74f8Zh9KYEfo27jpO5e-3I57VaPrUo44kH15kNPUqV73BOFLVa6RjPSWXZJgCiIzMydT9AkM-wsCpBHVhnaY0Gm4pUiqBDRLSdhgW9SRd-hz8bVAmPpC9hMsoVn4XjclPGKN0bJtvlG2OjfvsiR-PificLSYclIqzDkT7UPpBcNUnal1BNZ6VgGPXGWG2q29rESUQ0Phr37YYiSOtTzkeNeKH0esTOtzVpbnXTyXjq_SsXmL2QoWgVOiZmU-lNzzrIbTR3r0uWmSn1v6bzyWAS9S6aFUdxnb0zENR8SQ6IAyxV6N2Q \
        --ago=72--api-key=42vErWKs2oipGf6pYuBWnQPt
        cd PostDevToLi
        du -h posted_articles.db

    - name: Move DB to the artifact folder
      run: |
        mv ./PostDevToLi/posted_articles.db ./data/posted_articles.db
        git config --local user.email github-actions@github.com
        git config --local user.name github-actions
        git add .
        git commit -m "update"
        git push origin database
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

