name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    - name: Run Application (or Tests)
      run: |
        dotnet run --project PostDevToLi
        --api-key=42vErWKs2oipGf6pYuBWnQPt \
        --access-token=AQXD2BR_zOyTZ7bQlUkm0KNNfm4PwjpxupMQ_M1rowTA74f8Zh9KYEfo27jpO5e-3I57VaPrUo44kH15kNPUqV73BOFLVa6RjPSWXZJgCiIzMydT9AkM-wsCpBHVhnaY0Gm4pUiqBDRLSdhgW9SRd-hz8bVAmPpC9hMsoVn4XjclPGKN0bJtvlG2OjfvsiR-PificLSYclIqzDkT7UPpBcNUnal1BNZ6VgGPXGWG2q29rESUQ0Phr37YYiSOtTzkeNeKH0esTOtzVpbnXTyXjq_SsXmL2QoWgVOiZmU-lNzzrIbTR3r0uWmSn1v6bzyWAS9S6aFUdxnb0zENR8SQ6IAyxV6N2Q \
        --ago=72--api-key=42vErWKs2oipGf6pYuBWnQPt

    - name: Upload SQLite DB as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: posted-articles-db  # The name of the artifact
        path: ./PostDevToLi/bin/Debug/net8.0/posted_articles.db  # Ensure this points to your SQLite DB

