name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Get latest artifact run id
      run: |
        ARTIFACT_RUN_ID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=1" | jq '.artifacts[0].workflow_run.id')
        echo "artifact_run_id=$ARTIFACT_RUN_ID" >> $GITHUB_ENV
        echo "ARTIFACT_RUN_ID"
    # Attempt to download the artifact (if uploaded in the same or previous runs)
    - name: Download artifact (SQLite DB)
      uses: actions/download-artifact@v4
      with:
        name: posted-articles-db  # Ensure this is the exact artifact name used during the upload
        path: ./data/

    - name: Test
      run: dotnet test --no-build --verbosity normal
