name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Ensure data folder exists
      run: mkdir -p ./PostDevToLi/data
    
    - name: Download SQLite DB
      uses: actions/download-artifact@v4
      with:
        name: posted-articles-db
        path: ./data/
      continue-on-error: true 

    # Move the database to the correct location for your app
    - name: Move DB to the app folder
      run: |
        cd data
        ls
        mv ./data/posted_articles.db ./PostDevToLi/bin/Debug/net8.0/posted_articles.db
      continue-on-error: true
    - name: Run Application (or Tests)
      run: |
        dotnet run --project PostDevToLi/PostDevToLi.csproj -- \
        --api-key="${{ secrets.DEV_TO_API_KEY }}" \
          --access-token="${{ secrets.ACCESS_TOKEN }}" \
        --ago=72

    - name: Move DB to the artifact folder
      run: |
        ls
        mv ./PostDevToLi/bin/Debug/net8.0/posted_articles.db ./data/posted_articles.db

    - name: Upload SQLite DB as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: posted-articles-db  # The name of the artifact
        path: ./data/posted_articles.db
    - name: Download SQLite DB artifact
      uses: actions/download-artifact@v4
      with:
        name: posted-articles-db
        path: ./data/
      continue-on-error: true 

    - name: List files in data directory
      run: | 
        cd data
        ls

